Register Page Front OK
WildCodeSchool/2022-03-JS-Lille-project-3-g1-adan pull request #11
Opened 2022-06-14 09:35 UTC by LauraCourquin

2022-06-14 12:19 UTC, SDecambray approved these changes, later dismissed

2022-06-14 12:31 UTC, SDecambray submitted a review, later dismissed

2022-06-14 14:24 UTC, LuigiMenez requested changes
Fix minor

2022-06-14 14:24 UTC, LuigiMenez commented on frontend/src/App.jsx
> +          <Route path="/profile/:profileId" element={<Profile />} />
Indentation

2022-06-14 14:24 UTC, LuigiMenez commented on frontend/src/components/DemoProfile/index.jsx
> +
Why?

2022-06-14 15:26 UTC, LauraCourquin reviewed
Update App.jsx

2022-06-15 07:45 UTC, SDecambray approved these changes, later dismissed

2022-06-15 08:14 UTC, LuigiMenez approved these changes, later dismissed
Ok for me.

2022-06-15 08:43 UTC, LoicBrassart requested changes
Globally, beware of code quality and PR reviewing, everybody loses time when one is refused

2022-06-15 08:43 UTC, LoicBrassart commented on frontend/src/App.jsx
> +        <Route path="/" element={<Home />} />
I already saw this code one PR ago (and two PR ago, too)
Stop duplicating code (conflict-prone result) and please create your branches *from `dev`*

2022-06-15 08:43 UTC, LoicBrassart commented on frontend/src/components/Checkbox/index.jsx
> +}
... What's this ?
You created a full component to replace a `<input type="checkbox" />` with an image-in-a-button-in-a-div ? WHY ?! (v°_°v)

2022-06-15 08:43 UTC, LoicBrassart commented on frontend/src/components/RegisterArtist/index.jsx
> +  const hSubmit = (evt) => {
Be consistent in your functions' names

2022-06-15 08:43 UTC, LoicBrassart commented on frontend/src/components/RegisterArtist/index.jsx
> +              <button className="btnNext" type="submit">
Isn't it `<input type="submit" />` ?
(I may be wrong on this one, please check it out)

2022-06-15 08:48 UTC, LauraCourquin commented on frontend/src/components/Checkbox/index.jsx
> +}
I was told that checkboxes to style were complicated. 
I went for the simplest.

2022-06-15 08:51 UTC, LauraCourquin commented on frontend/src/components/RegisterArtist/index.jsx
> +              <button className="btnNext" type="submit">
You are right, I will change that.

2022-06-15 09:14 UTC, LauraCourquin reviewed
Update index.jsx

2022-06-15 09:17 UTC, SDecambray approved these changes, later dismissed

2022-06-15 13:06 UTC, LuigiMenez approved these changes, later dismissed
Ok for me.

2022-06-16 07:50 UTC, LoicBrassart commented on frontend/src/components/Checkbox/index.jsx
> +}
That's not really a good idea: it **looks** better but they're not checkboxes anymore (SEO & accessibility browsers will have a blast trying to explain this !)

2022-06-16 07:51 UTC, LoicBrassart submitted a review, later dismissed
NmE

2022-06-16 08:13 UTC, ghost commented
Resolve conflict with dev App.jsx

2022-06-16 08:28 UTC, SDecambray commented on frontend/src/App.jsx
> +        <Route path="/" element={<Home />} />
Done

2022-06-16 08:30 UTC, SDecambray submitted a review, later dismissed

2022-06-16 10:16 UTC, LuigiMenez approved these changes, later dismissed
Ok for me

2022-06-16 14:05 UTC, LoicBrassart approved these changes, later dismissed
NmE

2022-06-17 06:59 UTC, SDecambray approved these changes

2022-06-17 10:20 UTC, LuigiMenez approved these changes
Ok for me.

2022-06-17 15:10 UTC, LoicBrassart approved these changes
Much better!

2022-06-20 13:23 UTC, closed without merging