New Component last artist, created and finished
WildCodeSchool/2022-03-JS-Lille-project-3-g1-adan pull request #12
Opened 2022-06-14 15:26 UTC by Elfaram

2022-06-15 07:43 UTC, SDecambray submitted a review, later dismissed

2022-06-15 08:16 UTC, LuigiMenez submitted a review, later dismissed
Ok for me.

2022-06-15 08:48 UTC, LoicBrassart requested changes
Some evils to fix

2022-06-15 08:48 UTC, LoicBrassart commented on frontend/src/App.jsx
> +        <Route path="/RegisterArtistLast" element={<Register />} />
I don't recommend uppercase characters in urls

2022-06-15 08:48 UTC, LoicBrassart commented on frontend/src/components/RegisterArtistLast/index.jsx
> +  };
Please refactor these functoins

2022-06-15 08:48 UTC, LoicBrassart commented on frontend/src/components/RegisterArtistLast/index.jsx
> +              <option value="2">Auto-entrepreneur </option>
Use more meaningful values for your forms

2022-06-15 13:22 UTC, Elfaram reviewed
changes FormData and Values

2022-06-15 13:23 UTC, SDecambray submitted a review, later dismissed

2022-06-15 14:30 UTC, LuigiMenez submitted a review, later dismissed
Ok for me.

2022-06-16 07:51 UTC, LoicBrassart commented
Solve conflicts plz

2022-06-16 12:13 UTC, SDecambray approved these changes, later dismissed

2022-06-17 07:00 UTC, SDecambray commented
solve conflict

2022-06-17 07:01 UTC, SDecambray approved these changes

2022-06-17 10:15 UTC, LuigiMenez approved these changes
Ok for me.

2022-06-17 15:11 UTC, LoicBrassart approved these changes
Stop editing on GHub so often!

2022-06-17 15:11 UTC, LoicBrassart commented on frontend/src/components/RegisterArtistLast/index.jsx
> +    status: "",
Indentation

2022-06-19 14:56 UTC, merged