Home page 02
WildCodeSchool/2022-03-JS-Lille-project-3-g1-adan pull request #18
Opened 2022-06-16 10:27 UTC by ValentinCop

2022-06-16 12:26 UTC, SDecambray approved these changes, later dismissed

2022-06-17 09:02 UTC, LuigiMenez requested changes
Modified style

2022-06-17 09:02 UTC, LuigiMenez commented on frontend/src/pages/Home/style.jsx
> +  .about {
Possibility to make `.about, .connection p{display: none;}`

2022-06-17 09:19 UTC, SDecambray approved these changes

2022-06-17 09:19 UTC, SDecambray commented on frontend/src/pages/Home/style.jsx
> +  .about {
Donec

2022-06-17 10:25 UTC, LuigiMenez approved these changes
Ok for me.

2022-06-20 07:00 UTC, LoicBrassart approved these changes
SnE

2022-06-20 07:17 UTC, merged