worked on login component
WildCodeSchool/2022-03-JS-Lille-project-3-g1-adan pull request #26
Opened 2022-06-23 09:15 UTC by ValentinCop

2022-06-23 09:56 UTC, SDecambray approved these changes, later dismissed
Good for me

2022-06-24 06:43 UTC, LuigiMenez requested changes
Error handling, would be nice

2022-06-24 06:43 UTC, LuigiMenez commented on frontend/src/components/Login/index.jsx
> +      .then(() => {})
Error handling, would be nice

2022-06-24 14:53 UTC, SDecambray approved these changes, later dismissed
Ok for me

2022-06-27 06:59 UTC, LuigiMenez approved these changes, later dismissed
Ok for me.

2022-06-28 09:07 UTC, LoicBrassart requested changes
Fix this

2022-06-28 09:07 UTC, LoicBrassart commented on frontend/src/components/Login/index.jsx
> +      })
... Just nope:
- Useless
- Misuse of `console.warn` (you use it as a `console.log` authorized by ESLint :cry: )

2022-06-28 09:07 UTC, LoicBrassart commented on frontend/src/components/Login/index.jsx
> +        console.error("wrong login");
Even this is not really useful, you could instead dispatch a Toast notification ?

2022-07-04 08:39 UTC, SDecambray approved these changes, later dismissed
ok for me

2022-07-04 09:03 UTC, SDecambray submitted a review, later dismissed
ok for me

2022-07-04 09:05 UTC, LuigiMenez approved these changes, later dismissed
Ok for me.

2022-07-05 06:54 UTC, LoicBrassart commented
Missing validations

2022-07-05 06:56 UTC, SDecambray approved these changes
Ok for me

2022-07-05 06:59 UTC, closed without merging