Calendar front
WildCodeSchool/2022-03-JS-Lille-project-3-g1-adan pull request #27
Opened 2022-06-23 09:31 UTC by camillaume

2022-06-23 09:58 UTC, SDecambray submitted a review, later dismissed
Okey for me

2022-06-24 06:47 UTC, LuigiMenez submitted a review, later dismissed
Ok for me.

2022-06-24 07:11 UTC, LoicBrassart requested changes
Remove unnecessary code (or explain to me why you need it)

2022-06-24 07:11 UTC, LoicBrassart commented on frontend/src/components/CalendarComponent/index.jsx
> +});
May I know why you'e rexriting all the FR locales here ?

2022-06-24 12:05 UTC, camillaume commented on frontend/src/components/CalendarComponent/index.jsx
> +});
Because without this code, moment is in english

2022-07-04 08:43 UTC, SDecambray approved these changes
Ok for me

2022-07-04 09:26 UTC, LuigiMenez approved these changes
Ok for me.

2022-07-05 06:57 UTC, LoicBrassart approved these changes
SnE

2022-07-05 06:59 UTC, merged