fixed styled of the home page
WildCodeSchool/2022-03-JS-Lille-project-3-g1-adan pull request #39
Opened 2022-06-27 09:18 UTC by ValentinCop

2022-06-27 09:18 UTC, SDecambray approved these changes, later dismissed
ok for me

2022-06-27 15:33 UTC, LuigiMenez requested changes
That's a lot of auto

2022-06-27 15:33 UTC, LuigiMenez commented on frontend/src/pages/Home/style.jsx
> +    margin: 2rem auto auto auto;
That's a lot of auto

2022-06-28 08:04 UTC, SDecambray approved these changes
ok for me

2022-06-28 09:14 UTC, LoicBrassart approved these changes
SnE

2022-06-28 09:16 UTC, LuigiMenez approved these changes
Ok for me.

2022-06-28 09:20 UTC, merged