Create Header components
WildCodeSchool/2022-03-JS-Lille-project-3-g1-adan pull request #4
Opened 2022-06-08 14:04 UTC by Elfaram

Create a header component (burgerMenu and mobile version call in the component NavBar)

2022-06-08 16:24 UTC, SDecambray submitted a review, later dismissed

2022-06-10 08:05 UTC, SDecambray approved these changes, later dismissed

2022-06-10 10:58 UTC, LuigiMenez requested changes
No line blank and why empty div tags

2022-06-10 10:58 UTC, LuigiMenez commented on frontend/src/App.jsx
> +
Blank line

2022-06-10 10:58 UTC, LuigiMenez commented on frontend/src/components/Burger/index.jsx
> +        <div />
Why???

2022-06-10 12:58 UTC, Elfaram reviewed
blank ok, div menuburger ok

2022-06-10 12:58 UTC, Elfaram commented on frontend/src/components/Burger/index.jsx
> +        <div />
Div=MenuBurger

2022-06-10 12:59 UTC, LuigiMenez approved these changes
Ok for me.

2022-06-10 14:39 UTC, SDecambray submitted a review, later dismissed

2022-06-12 06:39 UTC, LuigiMenez requested changes
attention to the indentation

2022-06-12 06:39 UTC, LuigiMenez commented on frontend/src/App.jsx
> +      <div className="App">
Warning indentation

2022-06-13 07:22 UTC, Elfaram reviewed
Changed App.jsx indentation

2022-06-13 07:24 UTC, SDecambray approved these changes, later dismissed

2022-06-13 07:28 UTC, SDecambray approved these changes

2022-06-13 13:45 UTC, LuigiMenez approved these changes
Ok for me.

2022-06-14 06:43 UTC, LoicBrassart approved these changes
SnE, good job ;-)

2022-06-14 12:25 UTC, merged