Search result
WildCodeSchool/2022-03-JS-Lille-project-3-g1-adan pull request #48
Opened 2022-07-04 12:59 UTC by mastemm

2022-07-04 13:19 UTC, SDecambray submitted a review, later dismissed
Ok for me

2022-07-04 15:45 UTC, LuigiMenez requested changes
Fix minor

2022-07-04 15:45 UTC, LuigiMenez commented on frontend/src/components/BackButton/style.jsx
> +export default styled.div`
why styled.div, rather than styled.button

2022-07-04 15:45 UTC, LuigiMenez commented on frontend/src/components/GroupInfo/style.jsx
> +    /* align-items: center; */
dead code

2022-07-05 07:40 UTC, SDecambray submitted a review, later dismissed
Ok for me after fix

2022-07-05 08:48 UTC, LuigiMenez approved these changes, later dismissed
Ok for me.

2022-07-06 06:46 UTC, LoicBrassart approved these changes, later dismissed
SnE

2022-07-06 07:39 UTC, SDecambray approved these changes
Ok for me, it's just a conflict in router for one line

2022-07-06 07:47 UTC, LuigiMenez approved these changes
Ok for me.

2022-07-06 14:30 UTC, LoicBrassart approved these changes
SnE

2022-07-06 15:07 UTC, merged