Login
WildCodeSchool/2022-03-JS-Lille-project-3-g1-adan pull request #53
Opened 2022-07-05 12:25 UTC by ValentinCop

2022-07-05 12:31 UTC, SDecambray submitted a review, later dismissed
ok for me

2022-07-05 13:23 UTC, LuigiMenez requested changes
Not use redux thunks

2022-07-05 13:23 UTC, LuigiMenez commented on frontend/src/components/Login/index.jsx
> +        toast.success("Bienvenue !", {
The toast options, you can declare them in the toastcontainer, to avoid repeating them

2022-07-05 15:12 UTC, LuigiMenez approved these changes
Ok for me

2022-07-05 15:12 UTC, LuigiMenez commented on frontend/src/services/reducers/index.js
> +const mainReducer = combineReducers({ user });
the combineReducers is not useful if you only have one reducer

2022-07-06 07:08 UTC, SDecambray approved these changes
Ok for me

2022-07-06 14:33 UTC, LoicBrassart approved these changes
SnE

2022-07-06 15:07 UTC, merged