added globalStyle and created HomePage
WildCodeSchool/2022-03-JS-Lille-project-3-g1-adan pull request #6
Opened 2022-06-09 15:23 UTC by ValentinCop

2022-06-09 15:24 UTC, SDecambray approved these changes, later dismissed

2022-06-09 15:31 UTC, LuigiMenez requested changes
Fix minor

2022-06-09 15:31 UTC, LuigiMenez commented on frontend/src/pages/Home/index.jsx
> +      <section />
Why?

2022-06-09 15:31 UTC, LuigiMenez commented on frontend/src/pages/Home/index.jsx
> +      <section />
Why?

2022-06-09 15:31 UTC, LuigiMenez commented on frontend/index.html
> +    <link rel="preconnect" href="https://fonts.googleapis.com" />
Not import fonts in the index.html

2022-06-10 15:18 UTC, SDecambray approved these changes

2022-06-12 06:36 UTC, LuigiMenez approved these changes
Ok for me.

2022-06-13 06:42 UTC, LoicBrassart approved these changes
SnE

2022-06-13 07:24 UTC, merged