Fix style
WildCodeSchool/2022-03-JS-Lille-project-3-g1-adan pull request #67
Opened 2022-07-13 14:19 UTC by mastemm

2022-07-13 14:39 UTC, SDecambray requested changes
Just change the padding plz

2022-07-13 14:39 UTC, SDecambray commented on frontend/src/components/Login/style.jsx
>      .formBox {
padding : top right bottom left

2022-07-13 14:40 UTC, ghost requested changes

2022-07-13 14:40 UTC, SDecambray commented on frontend/src/components/Login/style.jsx
> +      padding-left: 7rem;
padding : vertical horizontal

2022-07-13 16:46 UTC, SDecambray approved these changes
Ok for me

2022-07-18 07:11 UTC, LuigiMenez approved these changes
Ok for me.

2022-07-18 08:16 UTC, LoicBrassart approved these changes
SnE

2022-07-18 09:38 UTC, merged