Search page
WildCodeSchool/2022-03-JS-Lille-project-3-g1-adan pull request #7
Opened 2022-06-09 20:36 UTC by camillaume

2022-06-10 07:01 UTC, SDecambray approved these changes, later dismissed

2022-06-10 08:40 UTC, LuigiMenez approved these changes, later dismissed
Ok for me.

2022-06-10 12:36 UTC, LoicBrassart requested changes
Put your backend url in your .env file to ease up deployment later

2022-06-10 12:36 UTC, LoicBrassart commented on frontend/src/pages/Search/index.jsx
> +        .get(`http://localhost:5000/searchs?needle=${formData.search}`)
Put this `http://localhost:5000` in your `.env` file

2022-06-13 06:33 UTC, SDecambray approved these changes, later dismissed

2022-06-13 13:33 UTC, LuigiMenez submitted a review, later dismissed
Ok for me.

2022-06-14 14:25 UTC, LuigiMenez approved these changes, later dismissed
Ok for me.

2022-06-15 07:57 UTC, SDecambray approved these changes, later dismissed

2022-06-15 08:11 UTC, LuigiMenez submitted a review, later dismissed
Ok for me.

2022-06-15 08:23 UTC, LoicBrassart requested changes
Please be careful when reviewing PRs

2022-06-15 08:23 UTC, LoicBrassart commented on backend/src/router.js
> +router.get("/artists", ArtistController.browse);
- not mix /items routes with useful ones
- delete /items routes (only useful as a template)
- use lowercase route names

2022-06-15 08:23 UTC, LoicBrassart commented on frontend/src/App.jsx
> +import "./App.css";
No CSS

2022-06-15 08:23 UTC, LoicBrassart commented on frontend/src/App.jsx
> +      <Route path="/profile" element={<Profile />} />
This route is declared THREE lines above ... Please review carefully

2022-06-15 08:57 UTC, SDecambray submitted a review, later dismissed
fix all change requiered

2022-06-15 13:04 UTC, ghost approved these changes

2022-06-15 14:31 UTC, LuigiMenez approved these changes
Ok for me.

2022-06-16 07:12 UTC, LoicBrassart commented
@SDecambray Please be careful about your commit messages, I have no idea of what you did by reading them...

2022-06-16 07:16 UTC, LoicBrassart approved these changes
No more Evil

2022-06-16 07:39 UTC, merged